# mkdocs使用说明(https://zhuanlan.zhihu.com/p/383582472)
# 官网地址(https://www.mkdocs.org/)
# github地址(https://github.com/mkdocs/mkdocs)
# 常用指令
# mkdocs serve 本地开启预览服务
# mkdocs gh-deploy --clean 创建一个gh-pages分支，并将当前目录中的site/目录下的内容推送到远程的gh-pages分支
site_name: Rings Api # 项目说明
site_author: yang.guo # 作者描述
site_description: Rings document # 文档描述
copyright: Copyright &copy; 2021 - 2021

repo_name: GitLab # 仓库地址标题
repo_url: https://gitlab.pengpengla.com/dhn-android/rings/dhn-android-rings # 链接地址

theme: # 配置主题选项
  name: 'material' # 主题名称(https://squidfunk.github.io/mkdocs-material/)
  palette:
    primary: indigo
  language: 'zh' # 设置语言为中文

markdown_extensions: # markdown语法设置
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed

nav: # 页面导航
  - SSH免密登录: index.md
  - Linux常用命令: commands.md